export const ANY_CHAR_MASK = '*';
export const NUMBER_CHAR_MASK = '9';
export const ALPHABETIC_CHAR_MASK = 'A';
export const ALPHANUMERIC_CHAR_MASK = '#';

export const ALL_VALID_MASKS = [ANY_CHAR_MASK, NUMBER_CHAR_MASK, ALPHABETIC_CHAR_MASK, ALPHANUMERIC_CHAR_MASK];

export const CHAR_CODE_FIRST_LETTER_UPPER = 65;
export const CHAR_CODE_LAST_LETTER_UPPER = 90;

export const CHAR_CODE_FIRST_NUMBER_UPPER = 48;
export const CHAR_CODE_LAST_NUMBER_UPPER = 57;
